{% set name = "instructor" %}
{% set version = "1.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/instructor-ai/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1a7a8f80103f0ed3dc7bb60689772e2e21f5e185586107f39022c983fa97204d
build:
  entry_points:
    - instructor = instructor.cli.cli:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]
  number: 0
# Though it is available upstream for 3.9, we’ll limit the package to Python 3.10 and above,
# since the newer typing syntax breaks all 3.9 builds.
requirements:
  host:
    - python
    - poetry-core
    - hatchling
    - pip
  run:
    - python
    - openai >=1.52.0,<2.0.0
    - pydantic >=2.8.0,<3.0.0
    - docstring_parser <1.0,>=0.16
    - typer <1.0.0,>=0.9.0
    - rich <14.0.0,>=13.7.0
    - aiohttp <4.0.0,>=3.9.1
    - requests <3.0.0,>=2.32.3
    - tenacity >=9.0.0,<10.0.0
    - pydantic-core >=2.18.0,<3.0.0
    - jiter <0.9,>=0.6.1
    - jinja2 <4.0.0,>=3.1.4
  run_constrained:
    - anthropic ==0.48.0
    - xmltodict >=0.13,<0.15
    - groq >=0.4.2,<0.14.0
    - cohere >=5.1.8,<6.0.0
    - google-generativeai >=0.8.2,<1.0.0
    - jsonref >=1.1.0,<2.0.0
    - google-cloud-aiplatform >=1.53.0,<2.0.0
    - cerebras-cloud-sdk >=1.5.0,<2.0.0
    - fireworks-ai >=0.15.4,<1.0.0
    - writer-sdk >=1.2.0,<2.0.0
    - boto3 >=1.34.0,<2.0.0
    - mistralai >=1.5.1,<2.0.0
    - openai >=1.52.0,<2.0.0
    - google-genai >=1.5.0
    - litellm >=1.35.31,<2.0.0

test:
  requires:
    - python
    - pip
  imports:
    - instructor
  commands:
    - pip check

about:
  home: https://github.com/jxnl/instructor
  summary: structured outputs for llm
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description : |
    Instructor is a Python library that provides a simple and efficient way to
    create structured outputs for large language models (LLMs). It allows you to
    define the structure of the output you want from the LLM, making it easier to
    work with the generated text. The library is designed to be easy to use and
    integrate into your existing projects.
  dev_url: https://github.com/jxnl/instructor
  doc_url: https://github.com/jxnl/instructor

extra:
  recipe-maintainers:
    - moritzwilksch
