{% set name = "instructor" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/567-labs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dc8b98d076dd0c922094c2b25777dc2b0a36b4f777e5ad06f22035a859187198
build:
  # Though it is available upstream for 3.9, we’ll limit the package to Python 3.10 and above,
  # since the newer typing syntax breaks all 3.9 builds.
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - instructor = instructor.cli.cli:app

requirements:
  host:
    - python
    - poetry-core
    - hatchling
    - pip
  run:
    - python
    - openai >=2.0.0,<3.0.0
    - pydantic >=2.8.0,<3.0.0
    - docstring_parser >=0.16,<1.0
    - typer >=0.9.0,<1.0.0
    - rich >=13.7.0,<15.0.0
    - aiohttp >=3.9.1,<4.0.0
    - tenacity >=8.2.3,<10.0.0
    - pydantic-core >=2.18.0,<3.0.0
    - jiter >=0.6.1,<0.14
    - jinja2 >=3.1.4,<4.0.0
    - requests >=2.32.3,<3.0.0

  run_constrained:
    # anthropic
    - anthropic ==0.88.0
    - xmltodict >=0.13,<1.1
    # groq
    - groq >=0.4.2,<1.1.0
    # cohere
    - cohere >=5.1.8,<6.0.0
    # vertexai
    - google-cloud-aiplatform >=1.53.0,<2.0.0
    - jsonref >=1.1.0,<2.0.0
    # cerebras_cloud_sdk
    - cerebras-cloud-sdk >=1.5.0,<2.0.0
    # fireworks-ai
    - fireworks-ai >=0.15.4,<1.0.0
    # writer
    - writer-sdk >=2.2.0,<3.0.0
    # bedrock
    - boto3 >=1.34.0,<2.0.0
    # mistral
    - mistralai >=1.5.1,<2.0.0
    # perplexity
    # - openai already pinned in run
    # google-genai
    - google-genai >=1.5.0
    # - jsonref, already pinned for vertexai
    # litellm
    - litellm >=1.35.31,<=1.83.0
    # xai
    - xai-sdk >=0.2.0  # [py>=310]
    # phonenumbers
    - phonenumbers >=8.13.33,<10.0.0
    # graphviz
    - graphviz >=0.20.3,<1.0.0
    # sqlmodel
    - sqlmodel >=0.0.22,<1.0.0
    # diskcache
    - diskcache >=5.6.3,<6.0.0
    # trafilatura
    - trafilatura >=1.12.2,<3.0.0
    # pydub
    - pydub >=0.25.1,<1.0.0
    # datasets
    - datasets >=3.0.1,<5.0.0

test:
  requires:
    - pip
  imports:
    - instructor
  commands:
    - pip check

about:
  home: https://python.useinstructor.com
  summary: structured outputs for llm
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description : |
    Instructor is a Python library that provides a simple and efficient way to
    create structured outputs for large language models (LLMs). It allows you to
    define the structure of the output you want from the LLM, making it easier to
    work with the generated text. The library is designed to be easy to use and
    integrate into your existing projects.
  dev_url: https://github.com/567-labs/instructor
  doc_url: https://github.com/567-labs/instructor

extra:
  recipe-maintainers:
    - moritzwilksch
